# Generated by Django 4.0.3 on 2022-05-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0004_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='utilisateur',
        ),
    ]
