# Generated by Django 4.0.5 on 2022-06-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0005_delete_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastruture',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
            ],
        ),
    ]
