# Generated by Django 4.0.5 on 2022-06-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0006_infrastruture'),
    ]

    operations = [
        migrations.CreateModel(
            name='partenaire',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=10)),
                ('lieu', models.CharField(max_length=10)),
            ],
        ),
    ]
