# Generated by Django 4.0.5 on 2022-06-12 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0007_partenaire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='partenaire',
            new_name='partenaires',
        ),
    ]
